---
- name: Reset DC1, DC2, and DCI to default configuration
  hosts: CloudVision
  connection: local
  gather_facts: no
  
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/initial_lab.yml"
      name: initial_lab
    
   

  - name: "Gather CVP facts {{inventory_hostname}}"
    arista.cvp.cv_facts:
    register: CVP_FACTS

  - name: "Configure devices on {{inventory_hostname}}"
    arista.cvp.cv_device:
      devices: "{{initial_lab}}"
      cvp_facts: '{{CVP_FACTS.ansible_facts}}'
      device_filter: ['leaf1-DC1']
      state: present
    register: CVP_DEVICES_RESULTS

  # - name: 'Display debug'
    #   debug:
    #     msg: '{{CVP_DEVICES_RESULTS}}'
